#!/bin/sh

UNAME="`uname`"

echo $UNAME | grep -e Windows_NT -e CYGWIN_NT >/dev/null
if [ $? -eq 0 ]; then
    PATH="$PATH;/usr/local/bin;c:/Perl/bin"
    export PATH
fi

myperl=perl

which $myperl >/dev/null || myperl="$PERL"

echo $UNAME | grep CYGWIN_NT >/dev/null
if [ $? -eq 0 ]; then
    "$myperl" $0.pl "`cygpath -a -w \"$1\"`"
else
    "$myperl" $0.pl "$@"
fi
